/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.ApplicationContextProvider;
import expo4to.gestion_AD.controlador.TrabajadorControlador;
import expo4to.gestion_AD.dto.TrabajadorDTO;
import expo4to.gestion_AD.util.CifradorContrasenas;
import expo4to.gestion_AD.util.Utilidades;
import lombok.ToString;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class ActualizarEmpleado extends JFrame {

    private static final Logger logger = Logger.getLogger(ActualizarEmpleado.class.getName());
    CifradorContrasenas cifrador;
    TrabajadorControlador trabajadorControlador;
    TrabajadorDTO trabajador;
    /**
     * Creates new form registrarEmpleado
     */
    public ActualizarEmpleado(TrabajadorDTO trabajador) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.trabajador = trabajador;
        trabajadorControlador = ApplicationContextProvider.getBean(TrabajadorControlador.class);
        cifrador = ApplicationContextProvider.getBean(CifradorContrasenas.class);

        jTextField1PrimerNombre.setText(this.trabajador.getNombre1());
        jTextFieldSegundoNombre.setText(this.trabajador.getNombre2());
        jTextFieldPrimerApellido.setText(this.trabajador.getApellido1());
        jTextFieldSegundoApellido.setText(this.trabajador.getApellido2());
        jTextFieldCedula.setText(this.trabajador.getCedula());
        jTextFieldCorreo.setText(this.trabajador.getCorreo());
        Direccion.setText(this.trabajador.getDireccion());
        jTextFieldFechaNacimiento.setText(String.valueOf(this.trabajador.getFechaN()));
        jTextFieldTelefono.setText(this.trabajador.getTelefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        jTextField1PrimerNombre = new JTextField();
        jLabel4 = new JLabel();
        jTextFieldSegundoNombre = new JTextField();
        jLabel5 = new JLabel();
        jTextFieldPrimerApellido = new JTextField();
        jLabel6 = new JLabel();
        jTextFieldSegundoApellido = new JTextField();
        jLabel7 = new JLabel();
        jTextFieldCedula = new JTextField();
        jLabel8 = new JLabel();
        jTextFieldCorreo = new JTextField();
        jLabel9 = new JLabel();
        jLabel10 = new JLabel();
        Direccion = new JTextField();
        jLabel2 = new JLabel();
        jTextFieldClave = new JPasswordField();
        jLabel11 = new JLabel();
        jTextFieldConfirmarClave = new JPasswordField();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jTextFieldFechaNacimiento = new JTextField();
        jToggleButton2 = new JToggleButton();
        jComboBoxCargo = new JComboBox<>();
        jTextFieldTelefono = new JTextField();
        jButtonGuardar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(255, 255, 255));

        jLabel1.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Empleados");

        jLabel3.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Primer Nombre");

        jLabel4.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Segundo Nombre");

        jLabel5.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Primer Apellido");

        jLabel6.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Segundo Apellido");

        jLabel7.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Cedula ");

        jLabel8.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Correo");

        jLabel9.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Telefono");

        jLabel10.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Direccion");

        jLabel2.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Clave");

        jLabel11.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Confirmar Clave");

        jLabel12.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Cargo");

        jLabel13.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Fecha de Nacimiento");

        jToggleButton2.setIcon(new ImageIcon(getClass().getResource("/icon/borrador (1).png"))); // NOI18N
        jToggleButton2.setBorder(null);
        jToggleButton2.setBorderPainted(false);
        jToggleButton2.setContentAreaFilled(false);
        jToggleButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jComboBoxCargo.setModel(new DefaultComboBoxModel<>(new String[] { "Cajero", "Jefe Control-Estudios", "Docente", " " }));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldFechaNacimiento, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel6, GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSegundoNombre, GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrimerApellido, GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSegundoApellido, GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1PrimerNombre, GroupLayout.Alignment.LEADING))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldCedula)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldCorreo)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldTelefono, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(88, 88, 88)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldClave)
                                    .addComponent(jTextFieldConfirmarClave)
                                    .addComponent(jComboBoxCargo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(Direccion))
                        .addGap(26, 26, 26)
                        .addComponent(jToggleButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCedula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldClave, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jToggleButton2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCorreo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldConfirmarClave, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCargo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Direccion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1PrimerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSegundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSegundoApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFechaNacimiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jButtonGuardar.setBackground(new Color(51, 153, 255));
        jButtonGuardar.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jButtonGuardar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jToggleButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    public void borrar() {

        jTextField1PrimerNombre.setText(this.trabajador.getNombre1());
        jTextFieldSegundoNombre.setText(this.trabajador.getNombre2());
        jTextFieldPrimerApellido.setText(this.trabajador.getApellido1());
        jTextFieldSegundoApellido.setText(this.trabajador.getApellido2());
        jTextFieldCedula.setText(this.trabajador.getCedula());
        jTextFieldCorreo.setText(this.trabajador.getCorreo());
        Direccion.setText(this.trabajador.getDireccion());
        jTextFieldFechaNacimiento.setText(String.valueOf(this.trabajador.getFechaN()));
        jTextFieldTelefono.setText(this.trabajador.getTelefono());

    }

    public void guardar() {

        TrabajadorDTO trabajador = this.trabajador;

        String clave = new String(jTextFieldClave.getPassword());
        String confirmarClave = new String(jTextFieldConfirmarClave.getPassword());

        if (!clave.equals(confirmarClave)) {
            JOptionPane.showMessageDialog(
                    null,
                    "Las contraseñas no son las mismas.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            trabajador.setCedula(jTextFieldCedula.getText());

            trabajador.setNombre1(jTextField1PrimerNombre.getText());
            trabajador.setNombre2(jTextFieldSegundoNombre.getText());
            trabajador.setApellido1(jTextFieldPrimerApellido.getText());
            trabajador.setApellido2(jTextFieldSegundoApellido.getText());

            trabajador.setDireccion(Direccion.getText());
            trabajador.setCorreo(jTextFieldCorreo.getText());
            trabajador.setTelefono(jTextFieldTelefono.getText());
            trabajador.setFechaN(Utilidades.convertirStringA_SqlDate(jTextFieldFechaNacimiento.getText()));
            trabajador.setEstado(true);

            String cargo = (String) jComboBoxCargo.getSelectedItem(); 
            switch (cargo) {
                case "Cajero":
                    trabajador.setRol(1);
                    break;
                case "Jefe Control-Estudios":
                    trabajador.setRol(2);
                    break;
                case "Docente":
                    trabajador.setRol(3);
                    break;
                case null:
                    break;
                default:
                    throw new IllegalStateException("Unexpected value: " + cargo);
            }

            if (!clave.trim().isEmpty()) {
                trabajador.setContrasena(cifrador.cifrarContrasena(clave));
            } else {
                trabajador.setContrasena(this.trabajador.getContrasena());
            }

            trabajadorControlador.guardarTrabajador(trabajador);

            JOptionPane.showMessageDialog(
                    null,
                    "Trabajador actualizado con éxito.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField Direccion;
    private JButton jButtonGuardar;
    private JComboBox<String> jComboBoxCargo;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JTextField jTextField1PrimerNombre;
    private JTextField jTextFieldCedula;
    private JPasswordField jTextFieldClave;
    private JPasswordField jTextFieldConfirmarClave;
    private JTextField jTextFieldCorreo;
    private JTextField jTextFieldFechaNacimiento;
    private JTextField jTextFieldPrimerApellido;
    private JTextField jTextFieldSegundoApellido;
    private JTextField jTextFieldSegundoNombre;
    private JTextField jTextFieldTelefono;
    private JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
