/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.ApplicationContextProvider;
import expo4to.gestion_AD.controlador.EstudianteControlador;
import expo4to.gestion_AD.controlador.RepresentanteControlador;
import expo4to.gestion_AD.dto.EstudianteDTO;
import expo4to.gestion_AD.dto.RepresentanteDTO;
import expo4to.gestion_AD.util.Utilidades;
import expo4to.gestion_AD.util.Verificador;

import javax.swing.*;
import java.util.NoSuchElementException;

/**
 *
 * @author usuario
 */
public class ActualizarEstudiantesRepresentantes extends JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ActualizarEstudiantesRepresentantes.class.getName());
    private RepresentanteControlador representanteControlador;
    private RepresentanteDTO representante;
    private EstudianteControlador estudianteControlador;
    private EstudianteDTO estudiante;
    private Verificador veri;
    boolean esEstudiante;

    /**
     * Creates new form actualizarEstudiantesRepresentantes
     */
    public ActualizarEstudiantesRepresentantes(boolean esEstudiante, EstudianteDTO estudiante, RepresentanteDTO representante) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        this.esEstudiante = esEstudiante;
        veri = ApplicationContextProvider.getBean(Verificador.class);

        if (this.esEstudiante) {
            estudianteControlador = ApplicationContextProvider.getBean(EstudianteControlador.class);
            this.estudiante = estudiante;
            jTextFieldPrimerNombreR.setEnabled(false);
            jTextField9SegundoNombreR.setEnabled(false);
            jTextFieldPrimerApellidoR.setEnabled(false);
            jTextFieldSegundoApellidoR.setEnabled(false);
            jTextFieldDireccionR.setEnabled(false);
            jTextFieldNacimientoR.setEnabled(false);
            jTextFieldTelefono.setEnabled(false);
            jButtonBorrarR.setEnabled(false);
            jTextFieldCedulaRepre.setEnabled(false);
            jButtonBorrarR.setEnabled(false);
            jButtonBuscar.setEnabled(false);
            jTextFieldCedulaR.setEnabled(false);

            jTextFieldPrimerNombre.setText(estudiante.getNombre1());
            jTextFieldSegundoNombre.setText(estudiante.getNombre2());
            jTextFieldPrimerApellido.setText(estudiante.getApellido1());
            jTextFieldSegundoApellido.setText(estudiante.getApellido2());
            jTextFieldDireccion.setText(estudiante.getDireccion());
            jTextFieldFechaNacimiento.setText(String.valueOf(estudiante.getFechaNacimiento()));
            jTextFieldCedulaRepre.setText(estudiante.getRepresentante().getCedula());
            jComboBoxGradoyAnio.setSelectedItem(estudiante.getGrado());


        } else {
            representanteControlador = ApplicationContextProvider.getBean(RepresentanteControlador.class);
            this.representante = representante;
            jTextFieldPrimerNombre.setEnabled(false);
            jTextFieldSegundoNombre.setEnabled(false);
            jTextFieldPrimerApellido.setEnabled(false);
            jTextFieldSegundoApellido.setEnabled(false);
            jTextFieldDireccion.setEnabled(false);
            jComboBoxGradoyAnio.setEnabled(false);
            jTextFieldFechaNacimiento.setEnabled(false);
            jButtonBuscar.setEnabled(false);
            jTextFieldCedulaRepre.setEnabled(false);
            jToggleButtonBorrar.setEnabled(false);
            jTextFieldCedulaR.setEnabled(false);
            jButtonBorrarR.setEnabled(false);

            jTextFieldPrimerNombreR.setText(representante.getNombre1());
            jTextField9SegundoNombreR.setText(representante.getNombre2());
            jTextFieldPrimerApellidoR.setText(representante.getApellido1());
            jTextFieldSegundoApellidoR.setText(representante.getApellido2());
            jTextFieldCedulaR.setText(representante.getCedula());
            jTextFieldDireccionR.setText(representante.getDireccion());
            jTextFieldNacimientoR.setText(String.valueOf(representante.getFechaN()));
            jTextFieldTelefono.setText(representante.getTelefono());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jPanel2 = new JPanel();
        jLabel3 = new JLabel();
        jTextFieldPrimerNombre = new JTextField();
        jLabel4 = new JLabel();
        jTextFieldSegundoNombre = new JTextField();
        jLabel5 = new JLabel();
        jTextFieldPrimerApellido = new JTextField();
        jLabel6 = new JLabel();
        jTextFieldSegundoApellido = new JTextField();
        jLabel7 = new JLabel();
        jTextFieldCedulaRepre = new JTextField();
        jLabel8 = new JLabel();
        jTextFieldDireccion = new JTextField();
        jLabel9 = new JLabel();
        jComboBoxGradoyAnio = new JComboBox<>();
        jLabel10 = new JLabel();
        jTextFieldFechaNacimiento = new JTextField();
        jToggleButtonBorrar = new JToggleButton();
        jPanel3 = new JPanel();
        jLabel11 = new JLabel();
        jTextFieldPrimerNombreR = new JTextField();
        jLabel12 = new JLabel();
        jTextField9SegundoNombreR = new JTextField();
        jLabel13 = new JLabel();
        jTextFieldPrimerApellidoR = new JTextField();
        jLabel14 = new JLabel();
        jTextFieldSegundoApellidoR = new JTextField();
        jLabel15 = new JLabel();
        jTextFieldCedulaR = new JTextField();
        jLabel16 = new JLabel();
        jTextFieldDireccionR = new JTextField();
        jLabel17 = new JLabel();
        jTextFieldTelefono = new JTextField();
        jLabel18 = new JLabel();
        jTextFieldNacimientoR = new JTextField();
        jButtonBorrarR = new JButton();
        jButtonBuscar = new JButton();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Estudiantes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registrar Representantes");

        jLabel3.setText("Primer Nombre");

        jLabel4.setText("Segundo Nombre");

        jLabel5.setText("Primer Apellido");

        jLabel6.setText("Segundo Apellido");

        jLabel7.setText("Cedula Representante");

        jLabel8.setText("Direccion");

        jLabel9.setText("Grado/Año");

        jComboBoxGradoyAnio.setModel(new DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", "4°", "5°", "6°", "1er año", "2do año", "3er año", "5to año" }));

        jLabel10.setText("Fecha de Nacimiento");

        jToggleButtonBorrar.setIcon(new ImageIcon(getClass().getResource("/icon/borrador (1).png"))); // NOI18N
        jToggleButtonBorrar.setBorder(null);
        jToggleButtonBorrar.setBorderPainted(false);
        jToggleButtonBorrar.setContentAreaFilled(false);
        jToggleButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBorrarActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSegundoNombre)
                    .addComponent(jTextFieldPrimerApellido)
                    .addComponent(jTextFieldSegundoApellido, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrimerNombre))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCedulaRepre)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDireccion)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxGradoyAnio, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldFechaNacimiento, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonBorrar)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCedulaRepre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButtonBorrar))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDireccion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradoyAnio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFechaNacimiento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSegundoNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSegundoApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLabel11.setText("Primer Nombre");

        jLabel12.setText("Segundo Nombre");

        jLabel13.setText("Primer Apellido");

        jLabel14.setText("Segundo Apellido");

        jLabel15.setText("Cedula");

        jLabel16.setText("Direccion");

        jLabel17.setText("Telefono");

        jLabel18.setText("Fecha de Nacimiento");

        jTextFieldNacimientoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNacimientoRActionPerformed(evt);
            }
        });

        jButtonBorrarR.setIcon(new ImageIcon(getClass().getResource("/icon/borrador (1).png"))); // NOI18N
        jButtonBorrarR.setBorder(null);
        jButtonBorrarR.setBorderPainted(false);
        jButtonBorrarR.setContentAreaFilled(false);
        jButtonBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarRActionPerformed(evt);
            }
        });

        jButtonBuscar.setIcon(new ImageIcon(getClass().getResource("/icon/lupa (1).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPrimerNombreR)
                    .addComponent(jTextField9SegundoNombreR)
                    .addComponent(jTextFieldPrimerApellidoR)
                    .addComponent(jTextFieldSegundoApellidoR, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCedulaR)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldDireccionR)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldTelefono)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNacimientoR, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrarR)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCedulaR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonBuscar)
                            .addComponent(jButtonBorrarR))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDireccionR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNacimientoR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerNombreR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9SegundoNombreR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerApellidoR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSegundoApellidoR, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jButton1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNacimientoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNacimientoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNacimientoRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBorrarActionPerformed
        // TODO add your handling code here:
        borrarCamposE();
    }//GEN-LAST:event_jToggleButtonBorrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        if (esEstudiante) buscarRepresentanteE();
        else buscarRepresentanteR();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarRActionPerformed
        // TODO add your handling code here:
        borrarCamposR();
    }//GEN-LAST:event_jButtonBorrarRActionPerformed

    public void borrarCamposE() {
        jTextFieldPrimerNombre.setText("");
        jTextFieldSegundoNombre.setText("");
        jTextFieldPrimerApellido.setText("");
        jTextFieldSegundoApellido.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldFechaNacimiento.setText("");
        jComboBoxGradoyAnio.setSelectedIndex(0);

        if (!jTextFieldCedulaR.isEnabled()) {
            jTextFieldCedulaRepre.setEnabled(true);
            jTextFieldCedulaRepre.setText("");
            jTextFieldCedulaR.setEnabled(true);
            jTextFieldCedulaR.setText("");
            jTextFieldPrimerNombreR.setText("");
            jTextField9SegundoNombreR.setText("");
            jTextFieldPrimerApellidoR.setText("");
            jTextFieldSegundoApellidoR.setText("");
            jTextFieldDireccionR.setText("");
            jTextFieldNacimientoR.setText("");
            jTextFieldTelefono.setText("");
        }
    }

    public void borrarCamposR() {

        if (!jTextFieldCedulaR.isEnabled()) {
            jTextFieldCedulaRepre.setEnabled(true);
            jTextFieldCedulaRepre.setText("");
        }

        jTextFieldPrimerNombreR.setText("");
        jTextField9SegundoNombreR.setText("");
        jTextFieldPrimerApellidoR.setText("");
        jTextFieldSegundoApellidoR.setText("");
        jTextFieldCedulaR.setText("");
        jTextFieldDireccionR.setText("");
        jTextFieldNacimientoR.setText("");
        jTextFieldTelefono.setText("");


        jTextFieldCedulaR.setEnabled(true);
        jTextFieldPrimerNombreR.setEnabled(true);
        jTextField9SegundoNombreR.setEnabled(true);
        jTextFieldPrimerApellidoR.setEnabled(true);
        jTextFieldSegundoApellidoR.setEnabled(true);
        jTextFieldDireccionR.setEnabled(true);
        jTextFieldNacimientoR.setEnabled(true);
        jTextFieldTelefono.setEnabled(true);
    }

    public void buscarRepresentanteE() {

        String cedula = jTextFieldCedulaR.getText().trim();

        if (!veri.esCedulaValida(cedula)) {
            JOptionPane.showMessageDialog(
                    null,
                    "El formato de la cédula es invalido.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        RepresentanteDTO encontrado;
        try {
            encontrado = representanteControlador.buscarRepresentantePorCedula(cedula);
            representante = encontrado;

        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (esEstudiante) {
            estudiante.setRepresentante(representante);
        }

        jTextFieldPrimerNombreR.setText(encontrado.getNombre1());
        jTextField9SegundoNombreR.setText(encontrado.getNombre2());
        jTextFieldPrimerApellidoR.setText(encontrado.getApellido1());
        jTextFieldSegundoApellidoR.setText(encontrado.getApellido2());
        jTextFieldDireccionR.setText(encontrado.getDireccion());
        jTextFieldNacimientoR.setText(String.valueOf(encontrado.getFechaN()));
        jTextFieldTelefono.setText(encontrado.getTelefono());
        jTextFieldCedulaR.setEnabled(false);
        jTextFieldPrimerNombreR.setEnabled(false);
        jTextField9SegundoNombreR.setEnabled(false);
        jTextFieldPrimerApellidoR.setEnabled(false);
        jTextFieldSegundoApellidoR.setEnabled(false);
        jTextFieldDireccionR.setEnabled(false);
        jTextFieldNacimientoR.setEnabled(false);
        jTextFieldTelefono.setEnabled(false);

        jTextFieldCedulaRepre.setText(encontrado.getCedula());
        jTextFieldCedulaRepre.setEnabled(false);
    }

    public void buscarRepresentanteR() {

        String cedula = jTextFieldCedulaR.getText();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debe ingresar una cédula para poder buscar.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        if (!veri.esCedulaValida(cedula)) {
            JOptionPane.showMessageDialog(
                    null,
                    "El formato de la cédula es invalido.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            representanteControlador.buscarRepresentantePorCedula(cedula);
            JOptionPane.showMessageDialog(
                    null,
                    "Cédula ya existente en la base de datos, intente de nuevo.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Cédula libre para nuevo registro",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );
            jTextFieldCedulaRepre.setText(jTextFieldCedulaR.getText());
        }

    }

    public void guardar() {

        if (esEstudiante) {

            try {
                estudiante.setNombre1(jTextFieldPrimerNombre.getText().trim());
                estudiante.setNombre2(jTextFieldSegundoNombre.getText().trim());
                estudiante.setApellido1(jTextFieldPrimerApellido.getText().trim());
                estudiante.setApellido2(jTextFieldSegundoApellido.getText().trim());
                estudiante.setGrado((String) jComboBoxGradoyAnio.getSelectedItem());
                estudiante.setDireccion(jTextFieldDireccion.getText().trim());
                estudiante.setEstado(true);
                estudiante.setFechaNacimiento(Utilidades.convertirStringA_SqlDate(jTextFieldFechaNacimiento.getText().trim()));
                estudiante.setNivelAcademico(Utilidades.determinarNivelAcademicoPorSufijo(estudiante.getGrado()));


                estudianteControlador.guardarEstudiante(estudiante);

                JOptionPane.showMessageDialog(
                        null,
                        "Estudiante actualizado con éxito.",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE
                );
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                System.err.println(e.getMessage());
            }

        } else {

            try {

                representante.setCedula(jTextFieldCedulaR.getText().trim());
                representante.setNombre1(jTextFieldPrimerNombreR.getText().trim());
                representante.setNombre2(jTextField9SegundoNombreR.getText().trim());
                representante.setApellido1(jTextFieldPrimerApellidoR.getText().trim());
                representante.setApellido2(jTextFieldSegundoApellidoR.getText().trim());
                representante.setDireccion(jTextFieldDireccionR.getText().trim());
                representante.setTelefono(jTextFieldTelefono.getText().trim());
                representante.setEstado(true);
                representante.setFechaN(Utilidades.convertirStringA_SqlDate(jTextFieldNacimientoR.getText().trim()));

                representanteControlador.guardarRepresentante(representante);

                JOptionPane.showMessageDialog(
                        null,
                        "Representante actualizado con éxito.",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE
                );
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                System.err.println(e.getMessage());
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButtonBorrarR;
    private JButton jButtonBuscar;
    private JComboBox<String> jComboBoxGradoyAnio;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel16;
    private JLabel jLabel17;
    private JLabel jLabel18;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JTextField jTextField9SegundoNombreR;
    private JTextField jTextFieldCedulaR;
    private JTextField jTextFieldCedulaRepre;
    private JTextField jTextFieldDireccion;
    private JTextField jTextFieldDireccionR;
    private JTextField jTextFieldFechaNacimiento;
    private JTextField jTextFieldNacimientoR;
    private JTextField jTextFieldPrimerApellido;
    private JTextField jTextFieldPrimerApellidoR;
    private JTextField jTextFieldPrimerNombre;
    private JTextField jTextFieldPrimerNombreR;
    private JTextField jTextFieldSegundoApellido;
    private JTextField jTextFieldSegundoApellidoR;
    private JTextField jTextFieldSegundoNombre;
    private JTextField jTextFieldTelefono;
    private JToggleButton jToggleButtonBorrar;
    // End of variables declaration//GEN-END:variables
}
