/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.ApplicationContextProvider;
import expo4to.gestion_AD.controlador.TrabajadorControlador;
import expo4to.gestion_AD.dto.EstudianteDTO;
import expo4to.gestion_AD.dto.TrabajadorDTO;
import expo4to.gestion_AD.vista.customize.EstudianteTableModel;
import expo4to.gestion_AD.vista.customize.TrabajadorTableModel;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */

public class gestionEmpleadosF extends javax.swing.JFrame {
    
    int yUbicacion, xUbicacion;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestionEmpleadosF.class.getName());
    private TrabajadorControlador trabajadorControlador;
    private TrabajadorDTO trabajadorActual;
    /**
     * Creates new form gestionEmpleadosF
     */
    public gestionEmpleadosF() {
        initComponents();
        trabajadorControlador = ApplicationContextProvider.getBean(TrabajadorControlador.class);
        actualizarLista();
        this.setLocationRelativeTo(null);
        ButtonActualizar.setEnabled(false);
        jTable1.getSelectionModel().addListSelectionListener(e -> {

            // Asegurarse de que el evento no sea el ajuste (ajusting) y que haya una selección válida
            if (!e.getValueIsAdjusting() && jTable1
                    .getSelectedRow() != -1) {

                // 1. Obtener la fila seleccionada en la VISTA (puede ser diferente al modelo si está ordenada)
                int filaSeleccionadaVista = jTable1.getSelectedRow();

                // 2. Mapear esa fila de la VISTA a la fila REAL del MODELO (si la tabla está ordenada)
                int filaModelo = jTable1.convertRowIndexToModel(filaSeleccionadaVista);

                // 3. Obtener el objeto DTO completo
                TrabajadorTableModel modelo = (TrabajadorTableModel) jTable1.getModel();

                // 4. ALMACENAR esta referencia en una variable de clase para su uso posterior
                this.trabajadorActual = modelo.getTrabajadorAt(filaModelo);

                // Opcional: Habilitar el botón de Actualizar/Editar
                ButtonActualizar.setEnabled(true);
            } else {
                // Ninguna fila seleccionada o deselección
                this.trabajadorActual = null;
                ButtonActualizar.setEnabled(false);
            }
        });


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ButtonAgregar = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonArchivar = new javax.swing.JButton();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonCerrarPrograma = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonMinimiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Empleados");

        ButtonAgregar.setBackground(new java.awt.Color(51, 153, 255));
        ButtonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonAgregar.setText("Agregar");
        ButtonAgregar.setBorderPainted(false);
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        ButtonActualizar.setBackground(new java.awt.Color(51, 153, 255));
        ButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.setBorderPainted(false);
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonArchivar.setBackground(new java.awt.Color(255, 51, 51));
        ButtonArchivar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonArchivar.setText("Archivar");
        ButtonArchivar.setBorderPainted(false);

        jComboBoxFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cedula", "Nombres", "Apellidos", "Cargo", "Fecha Nacimiento", "Telefono", "Estado", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jButtonCerrarPrograma.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCerrarPrograma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarPrograma.setText("X");
        jButtonCerrarPrograma.setBorderPainted(false);
        jButtonCerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarProgramaActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarSesion.setText("Atrás");
        jButtonCerrarSesion.setBorderPainted(false);
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jButtonMinimiza.setBackground(new java.awt.Color(51, 153, 255));
        jButtonMinimiza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMinimiza.setText("_");
        jButtonMinimiza.setBorderPainted(false);
        jButtonMinimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1097, Short.MAX_VALUE)
                .addComponent(jButtonCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMinimiza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrarPrograma)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarPrograma)
                    .addComponent(jButtonCerrarSesion)
                    .addComponent(jButtonMinimiza))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ButtonAgregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButtonActualizar))
                                    .addComponent(jLabel1))
                                .addGap(95, 95, 95)
                                .addComponent(ButtonArchivar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAgregar)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonArchivar)
                    .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        registrarEmpleado registrar = new registrarEmpleado();
        registrar.setVisible(true);     
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        ActualizarEmpleado actualizar = new ActualizarEmpleado(trabajadorActual);
        actualizar.setVisible(true);
        actualizarLista();
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void jButtonCerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarProgramaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar todo el programa?", "Confirmación.", JOptionPane.YES_NO_OPTION);

        switch (opcion){
            case JOptionPane.YES_OPTION:
            System.out.println("Cerrando el programa.");
            System.exit(0);
            break;
            case JOptionPane.NO_OPTION:
            System.out.println("No se cerró el programa.");
            break;
            case JOptionPane.CANCEL_OPTION:
            System.out.println("No se cerrará el programa, acción cancelada.");
            break;
            case JOptionPane.CLOSED_OPTION:
            System.out.println("No se cerrará el programa. Confirmación cerrada.");
            break;
            default:
            System.out.println("Opción desconocida.");

        }
    }//GEN-LAST:event_jButtonCerrarProgramaActionPerformed

    private void jButtonMinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizaActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizaActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - xUbicacion, point.y - yUbicacion);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xUbicacion = evt.getX();
        yUbicacion = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        dispose();
        ControlEstudiosHomeF controlEstudiosHomeF = new ControlEstudiosHomeF();
        setUndecorated(false);
        controlEstudiosHomeF.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    public void actualizarLista(){
        List<TrabajadorDTO> trabajadores = trabajadorControlador.listarTrabajadores();

        if (trabajadores.isEmpty()){
            JOptionPane.showMessageDialog(
                    null,
                    "No hay representantes registrados en el sistema",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        TrabajadorTableModel tableModel = new TrabajadorTableModel(trabajadores);
        jTable1.setModel(tableModel);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonArchivar;
    private javax.swing.JButton jButtonCerrarPrograma;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonMinimiza;
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
