/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.TrabajadorControlador;
import expo4to.gestion_AD.dto.TrabajadorDTO;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.NoSuchElementException;

/**
 *
 * @author usuario
 */
@Component
public class login extends javax.swing.JFrame {
    
    private int xUbicacion, yUbicacion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    private final TrabajadorControlador trabajadorControlador;
    /**
     * Creates new form login
     */
    public login() {

        this.trabajadorControlador = expo4to.gestion_AD.controlador.ApplicationContextProvider.getBean(TrabajadorControlador.class);
        initComponents();
        setLocationRelativeTo(null); // centra la ventana en pantalla


        campoContra.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Llama a la función cuando se presiona Enter
                iniciarSesion();
            }
        });
        correoCampo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Llama a la función cuando se presiona Enter
                iniciarSesion();
            }
        });
        correoCampo.requestFocusInWindow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        correoCampo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        campoContra = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCerrarPrograma = new javax.swing.JButton();
        jButtonMinimiza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Iniciar Sesion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo Electronico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        correoCampo.setForeground(new java.awt.Color(0, 0, 0));
        correoCampo.setText("tu-correo@ejemplo.com");
        correoCampo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correoCampoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoCampoFocusLost(evt);
            }
        });
        correoCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoCampoActionPerformed(evt);
            }
        });
        jPanel1.add(correoCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        loginButton.setBackground(new java.awt.Color(0, 0, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Iniciar Sesion");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 250, -1));

        campoContra.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 250, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo_liceo.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 430, 360));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButtonCerrarPrograma.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCerrarPrograma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarPrograma.setText("X");
        jButtonCerrarPrograma.setBorderPainted(false);
        jButtonCerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarProgramaActionPerformed(evt);
            }
        });

        jButtonMinimiza.setBackground(new java.awt.Color(51, 153, 255));
        jButtonMinimiza.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonMinimiza.setText("_");
        jButtonMinimiza.setBorderPainted(false);
        jButtonMinimiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addComponent(jButtonMinimiza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrarPrograma)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarPrograma)
                    .addComponent(jButtonMinimiza))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoCampoActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    
        iniciarSesion();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void correoCampoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoCampoFocusGained
        if (correoCampo.getText().equals("tu-correo@ejemplo.com") || correoCampo.getText().isEmpty()){
            correoCampo.setText("");
            correoCampo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_correoCampoFocusGained

    private void correoCampoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoCampoFocusLost
        if (correoCampo.getText().isEmpty() || correoCampo.getText().equals("tu-correo@ejemplo.com")){
            correoCampo.setText("tu-correo@ejemplo.com");
            correoCampo.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_correoCampoFocusLost

    private void jButtonCerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarProgramaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea cerrar todo el programa?", "Confirmación.", JOptionPane.YES_NO_OPTION);

        switch (opcion){
            case JOptionPane.YES_OPTION:
            System.out.println("Cerrando el programa.");
            System.exit(0);
            break;
            case JOptionPane.NO_OPTION:
            System.out.println("No se cerró el programa.");
            break;
            case JOptionPane.CANCEL_OPTION:
            System.out.println("No se cerrará el programa, acción cancelada.");
            break;
            case JOptionPane.CLOSED_OPTION:
            System.out.println("No se cerrará el programa. Confirmación cerrada.");
            break;
            default:
            System.out.println("Opción desconocida.");

        }
    }//GEN-LAST:event_jButtonCerrarProgramaActionPerformed

    private void jButtonMinimizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizaActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizaActionPerformed
    
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - xUbicacion, point.y - yUbicacion);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xUbicacion = evt.getX();
        yUbicacion = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void iniciarSesion() {

        if (correoCampo.getText().trim().isEmpty() || correoCampo.getText().equals("tu-correo@ejemplo.com")) {
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor ingrese un correo.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        if (campoContra.getPassword().length == 0) {
            JOptionPane.showMessageDialog(
                    null,
                    "La contraseña no puede quedar vacia.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        TrabajadorDTO dto;
        try {
            dto = trabajadorControlador.loginTrabajador(
                    correoCampo.getText().trim(), campoContra);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Correo o contraseña incorrecta, intente de nuevo.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Correo no registrado en el sistema, intente de nuevo.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Integer rol = dto.getRol();
        dto.setContrasena("");
        campoContra.setText("");

        switch (rol) {
            case 1:
                new RegistrarPagoF(dto).setVisible(true);
                dispose();
                break;
            case 2:
                new ProfesorHomeF(dto).setVisible(true);
                dispose();
                break;
            case 3:
                new ControlEstudiosHomeF().setVisible(true);
                dispose();
                break;
            default:
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JTextField correoCampo;
    private javax.swing.JButton jButtonCerrarPrograma;
    private javax.swing.JButton jButtonMinimiza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
