/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.ApplicationContextProvider;
import expo4to.gestion_AD.controlador.EstudianteControlador;
import expo4to.gestion_AD.controlador.RepresentanteControlador;
import expo4to.gestion_AD.dto.EstudianteDTO;
import expo4to.gestion_AD.dto.RepresentanteDTO;
import expo4to.gestion_AD.util.Utilidades;
import expo4to.gestion_AD.util.Verificador;

import javax.swing.*;
import java.sql.Date;
import java.util.NoSuchElementException;

/**
 *
 * @author usuario
 */
public class registrarEstudiantesRepresentantes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registrarEstudiantesRepresentantes.class.getName());
    private RepresentanteControlador representanteControlador;
    private RepresentanteDTO representante;
    private EstudianteControlador estudianteControlador;
    private EstudianteDTO estudiante = new EstudianteDTO();
    private Verificador veri;
    boolean esEstudiante;
    boolean puedeGuardar;

    /**
     * Creates new form actualizarEstudiantesRepresentantes
     */
    public registrarEstudiantesRepresentantes(boolean esEstudiante) {
        initComponents();
        setLocationRelativeTo(null);
        this.esEstudiante = esEstudiante;
        representanteControlador = ApplicationContextProvider.getBean(RepresentanteControlador.class);
        estudianteControlador = ApplicationContextProvider.getBean(EstudianteControlador.class);
        veri = ApplicationContextProvider.getBean(Verificador.class);
        jButton1.setEnabled(false);

        if (esEstudiante) {
            jTextFieldPrimerNombreR.setEnabled(false);
            jTextField9SegundoNombreR.setEnabled(false);
            jTextFieldPrimerApellidoR.setEnabled(false);
            jTextFieldSegundoApellidoR.setEnabled(false);
            jTextFieldDireccionR.setEnabled(false);
            jTextFieldNacimientoR.setEnabled(false);
            jTextFieldTelefono.setEnabled(false);
            jButtonBorrarR.setEnabled(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrimerNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSegundoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrimerApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSegundoApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCedulaRepre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxGradoyAnio = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jToggleButtonBorrar = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPrimerNombreR = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9SegundoNombreR = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPrimerApellidoR = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldSegundoApellidoR = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCedulaR = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldDireccionR = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNacimientoR = new javax.swing.JTextField();
        jButtonBorrarR = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Estudiantes");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Registrar Representantes");

        jLabel3.setText("Primer Nombre");

        jLabel4.setText("Segundo Nombre");

        jLabel5.setText("Primer Apellido");

        jLabel6.setText("Segundo Apellido");

        jLabel7.setText("Cedula Representante");

        jLabel8.setText("Direccion");

        jLabel9.setText("Grado/Año");

        jComboBoxGradoyAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1°", "2°", "3°", "4°", "5°", "6°", "1er año", "2do año", "3er año", "5to año" }));

        jLabel10.setText("Fecha de Nacimiento");

        jToggleButtonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrador (1).png"))); // NOI18N
        jToggleButtonBorrar.setBorder(null);
        jToggleButtonBorrar.setBorderPainted(false);
        jToggleButtonBorrar.setContentAreaFilled(false);
        jToggleButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSegundoNombre)
                    .addComponent(jTextFieldPrimerApellido)
                    .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrimerNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCedulaRepre)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDireccion)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxGradoyAnio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonBorrar)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCedulaRepre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToggleButtonBorrar))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGradoyAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jLabel11.setText("Primer Nombre");

        jLabel12.setText("Segundo Nombre");

        jLabel13.setText("Primer Apellido");

        jLabel14.setText("Segundo Apellido");

        jLabel15.setText("Cedula");

        jLabel16.setText("Direccion");

        jLabel17.setText("Telefono");

        jLabel18.setText("Fecha de Nacimiento");

        jTextFieldNacimientoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNacimientoRActionPerformed(evt);
            }
        });

        jButtonBorrarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/borrador (1).png"))); // NOI18N
        jButtonBorrarR.setBorder(null);
        jButtonBorrarR.setBorderPainted(false);
        jButtonBorrarR.setContentAreaFilled(false);
        jButtonBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarRActionPerformed(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lupa (1).png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPrimerNombreR)
                    .addComponent(jTextField9SegundoNombreR)
                    .addComponent(jTextFieldPrimerApellidoR)
                    .addComponent(jTextFieldSegundoApellidoR, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCedulaR)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldDireccionR)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldTelefono)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldNacimientoR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrarR)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCedulaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonBuscar)
                            .addComponent(jButtonBorrarR))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDireccionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNacimientoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField9SegundoNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrimerApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSegundoApellidoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jButton1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNacimientoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNacimientoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNacimientoRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBorrarActionPerformed
        // TODO add your handling code here:
        borrarCamposE();
    }//GEN-LAST:event_jToggleButtonBorrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        if (esEstudiante) buscarRepresentanteE();
        else buscarRepresentanteR();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarRActionPerformed
        // TODO add your handling code here:
        borrarCamposR();
    }//GEN-LAST:event_jButtonBorrarRActionPerformed

    public void borrarCamposE() {
        jTextFieldPrimerNombre.setText("");
        jTextFieldSegundoNombre.setText("");
        jTextFieldPrimerApellido.setText("");
        jTextFieldSegundoApellido.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldFechaNacimiento.setText("");
        jComboBoxGradoyAnio.setSelectedIndex(0);

        if (!jTextFieldCedulaR.isEnabled()) {
            jTextFieldCedulaRepre.setEnabled(true);
            jTextFieldCedulaRepre.setText("");
            jTextFieldCedulaR.setEnabled(true);
            jTextFieldCedulaR.setText("");
            jTextFieldPrimerNombreR.setText("");
            jTextField9SegundoNombreR.setText("");
            jTextFieldPrimerApellidoR.setText("");
            jTextFieldSegundoApellidoR.setText("");
            jTextFieldDireccionR.setText("");
            jTextFieldNacimientoR.setText("");
            jTextFieldTelefono.setText("");
        }
    }

    public void borrarCamposR() {

        if (!jTextFieldCedulaR.isEnabled()) {
            jTextFieldCedulaRepre.setEnabled(true);
            jTextFieldCedulaRepre.setText("");
        }

        jTextFieldPrimerNombreR.setText("");
        jTextField9SegundoNombreR.setText("");
        jTextFieldPrimerApellidoR.setText("");
        jTextFieldSegundoApellidoR.setText("");
        jTextFieldCedulaR.setText("");
        jTextFieldDireccionR.setText("");
        jTextFieldNacimientoR.setText("");
        jTextFieldTelefono.setText("");


        jTextFieldCedulaR.setEnabled(true);
        jTextFieldPrimerNombreR.setEnabled(true);
        jTextField9SegundoNombreR.setEnabled(true);
        jTextFieldPrimerApellidoR.setEnabled(true);
        jTextFieldSegundoApellidoR.setEnabled(true);
        jTextFieldDireccionR.setEnabled(true);
        jTextFieldNacimientoR.setEnabled(true);
        jTextFieldTelefono.setEnabled(true);
    }

    public void buscarRepresentanteE() {

        String cedula = jTextFieldCedulaR.getText().trim();

        if (!veri.esCedulaValida(cedula)) {
            JOptionPane.showMessageDialog(
                    null,
                    "El formato de la cédula es invalido.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            jButton1.setEnabled(false);
            return;
        }

        RepresentanteDTO encontrado;
        try {
            encontrado = representanteControlador.buscarRepresentantePorCedula(cedula);
            representante = encontrado;
            jButton1.setEnabled(true);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE
            );
            jButton1.setEnabled(false);
            return;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            jButton1.setEnabled(false);
            return;
        }

        jTextFieldPrimerNombreR.setText(encontrado.getNombre1());
        jTextField9SegundoNombreR.setText(encontrado.getNombre2());
        jTextFieldPrimerApellidoR.setText(encontrado.getApellido1());
        jTextFieldSegundoApellidoR.setText(encontrado.getApellido2());
        jTextFieldDireccionR.setText(encontrado.getDireccion());
        jTextFieldNacimientoR.setText(String.valueOf(encontrado.getFechaN()));
        jTextFieldTelefono.setText(encontrado.getTelefono());
        jTextFieldCedulaR.setEnabled(false);
        jTextFieldPrimerNombreR.setEnabled(false);
        jTextField9SegundoNombreR.setEnabled(false);
        jTextFieldPrimerApellidoR.setEnabled(false);
        jTextFieldSegundoApellidoR.setEnabled(false);
        jTextFieldDireccionR.setEnabled(false);
        jTextFieldNacimientoR.setEnabled(false);
        jTextFieldTelefono.setEnabled(false);

        jTextFieldCedulaRepre.setText(encontrado.getCedula());
        jTextFieldCedulaRepre.setEnabled(false);
    }

    public void buscarRepresentanteR() {

        String cedula = jTextFieldCedulaR.getText();

        if (cedula.isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debe ingresar una cédula para poder buscar.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            jButton1.setEnabled(false);
            return;
        }

        if (!veri.esCedulaValida(cedula)) {
            JOptionPane.showMessageDialog(
                    null,
                    "El formato de la cédula es invalido.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            jButton1.setEnabled(false);
            return;
        }

        try {
            representanteControlador.buscarRepresentantePorCedula(cedula);
            JOptionPane.showMessageDialog(
                    null,
                    "Cédula ya existente en la base de datos, intente de nuevo.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );
            jButton1.setEnabled(false);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Cédula libre para nuevo registro",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE
            );
            jTextFieldCedulaRepre.setText(jTextFieldCedulaR.getText());
            jButton1.setEnabled(true);
        }

    }

    public void guardar() {

        if (esEstudiante) {

            try {
                estudiante.setNombre1(jTextFieldPrimerNombre.getText().trim());
                estudiante.setNombre2(jTextFieldSegundoNombre.getText().trim());
                estudiante.setApellido1(jTextFieldPrimerApellido.getText().trim());
                estudiante.setApellido2(jTextFieldSegundoApellido.getText().trim());
                estudiante.setGrado((String) jComboBoxGradoyAnio.getSelectedItem());
                estudiante.setDireccion(jTextFieldDireccion.getText().trim());
                estudiante.setEstado(true);
                estudiante.setFechaNacimiento(Utilidades.convertirStringA_SqlDate(jTextFieldFechaNacimiento.getText().trim()));
                estudiante.setNivelAcademico(Utilidades.determinarNivelAcademicoPorSufijo(estudiante.getGrado()));
                estudiante.setRepresentante(representante);

                estudianteControlador.guardarEstudiante(estudiante);

                JOptionPane.showMessageDialog(
                        null,
                        "Estudiante guardado con éxito.",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE
                );
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                System.err.println(e.getMessage());
            }

        } else {

            try {

                representante = new RepresentanteDTO();
                estudiante = new EstudianteDTO();

                estudiante.setNombre1(jTextFieldPrimerNombre.getText().trim());
                estudiante.setNombre2(jTextFieldSegundoNombre.getText().trim());
                estudiante.setApellido1(jTextFieldPrimerApellido.getText().trim());
                estudiante.setApellido2(jTextFieldSegundoApellido.getText().trim());
                estudiante.setGrado((String) jComboBoxGradoyAnio.getSelectedItem());
                estudiante.setDireccion(jTextFieldDireccion.getText().trim());
                estudiante.setEstado(true);
                estudiante.setFechaNacimiento(Utilidades.convertirStringA_SqlDate(jTextFieldFechaNacimiento.getText().trim()));
                estudiante.setNivelAcademico(Utilidades.determinarNivelAcademicoPorSufijo(estudiante.getGrado()));

                representante.setCedula(jTextFieldCedulaRepre.getText().trim());
                representante.setNombre1(jTextFieldPrimerNombreR.getText().trim());
                representante.setNombre2(jTextField9SegundoNombreR.getText().trim());
                representante.setApellido1(jTextFieldPrimerApellidoR.getText().trim());
                representante.setApellido2(jTextFieldSegundoApellidoR.getText().trim());
                representante.setDireccion(jTextFieldDireccionR.getText().trim());
                representante.setTelefono(jTextFieldTelefono.getText().trim());
                representante.setEstado(true);
                representante.setFechaN(Utilidades.convertirStringA_SqlDate(jTextFieldNacimientoR.getText().trim()));

                if (!estudiante.getRepresentante().getCedula().contains(representante.getCedula())) {
                    JOptionPane.showMessageDialog(
                            null,
                            "La cedula del estudiante debe ser la misma del representante.",
                            "Alerta",
                            JOptionPane.WARNING_MESSAGE
                    );
                    jButton1.setEnabled(false);
                    return;
                }

                estudiante.setRepresentante(representante);
                representante.addEstudiante(estudiante);

                representanteControlador.guardarRepresentante(representante);

                JOptionPane.showMessageDialog(
                        null,
                        "Representante y estudiante guardados con éxito.",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE
                );
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        null,
                        e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                System.err.println(e.getMessage());
            }

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrarR;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxGradoyAnio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField9SegundoNombreR;
    private javax.swing.JTextField jTextFieldCedulaR;
    private javax.swing.JTextField jTextFieldCedulaRepre;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDireccionR;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldNacimientoR;
    private javax.swing.JTextField jTextFieldPrimerApellido;
    private javax.swing.JTextField jTextFieldPrimerApellidoR;
    private javax.swing.JTextField jTextFieldPrimerNombre;
    private javax.swing.JTextField jTextFieldPrimerNombreR;
    private javax.swing.JTextField jTextFieldSegundoApellido;
    private javax.swing.JTextField jTextFieldSegundoApellidoR;
    private javax.swing.JTextField jTextFieldSegundoNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JToggleButton jToggleButtonBorrar;
    // End of variables declaration//GEN-END:variables
}
