/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expo4to.gestion_AD.vista;

import expo4to.gestion_AD.controlador.*;
import expo4to.gestion_AD.dto.*;
import expo4to.gestion_AD.mapper.AnoEscolarMapper;
import expo4to.gestion_AD.vista.customize.EstudianteRenderer;
import expo4to.gestion_AD.vista.customize.TipoPagoRenderer;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.NoSuchElementException;

/**
 *
 * @author usuario
 */
public class RegistrarPagoF extends javax.swing.JFrame {

    private final RepresentanteControlador  representanteControlador;
    private final PagoControlador pagoControlador;
    private final TipoPagoControlador tipoPagoControlador;
    private final AnoEscolarControlador anoEscolarControlador;
    private final TrabajadorDTO trabajador;
    private RepresentanteDTO representante;
    private EstudianteDTO estudiante;
    private PagoReciboDTO recibo = new PagoReciboDTO();
    private TipoPagoDTO tipoPagoDTO;
    private DetallesPagoDTO mesAPagar;
    private String metodoPago;
    private boolean esAbono = false;
    private static final List<String> MESES_ESCOLARES = Arrays.asList(
            "Septiembre", "Octubre", "Noviembre", "Diciembre",
            "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto"
    );

    /**
     * Creates new form RegistrarPagoF
     */
    public RegistrarPagoF(TrabajadorDTO trabajador) {
        setUndecorated(true);
        this.trabajador = trabajador;
        this.representanteControlador = ApplicationContextProvider.getBean(RepresentanteControlador.class);
        this.pagoControlador = ApplicationContextProvider.getBean(PagoControlador.class);
        this.tipoPagoControlador = ApplicationContextProvider.getBean(TipoPagoControlador.class);
        this.anoEscolarControlador = ApplicationContextProvider.getBean(AnoEscolarControlador.class);
        initComponents();

        comboEstudiantes.setRenderer(new EstudianteRenderer());
        jComboBoxTipoPago.setRenderer(new TipoPagoRenderer());

        // Desactivar los campos hasta que busque un representante y seleccione un estudiante.
        jTextFieldMonto.setEnabled(false);
        jTextFieldConceptoPago.setEnabled(false);
        jTextFieldReferencia.setEnabled(false);
        jComboBoxTipoPago.setEnabled(false);
        jButtonEfectivo.setEnabled(false);
        ButtonTarjeta.setEnabled(false);
        ButtonTransferencia.setEnabled(false);
        ButtonAbono.setEnabled(false);
        ButtonConsultar.setEnabled(false);
        comboEstudiantes.setEnabled(false);

        // 1. Crear el objeto Date a partir de los milisegundos
        Date fecha = new Date(System.currentTimeMillis());

        // 2. Definir el formato (yyyy para año, MM para mes, dd para día)
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy/MM/dd");

        // 3. Formatear la fecha
        String fechaFormateada = formatter.format(fecha);

        // 4. Asignar al JTextField
        datosFecha.setText(fechaFormateada);

        java.util.List<TipoPagoDTO> tipos = tipoPagoControlador.listarTipoTapos();
        jComboBoxTipoPago.addItem(null);
        for (TipoPagoDTO dto : tipos) {
            jComboBoxTipoPago.addItem(dto);
        }

        jTextFieldCedulaRepre.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Llama a la función cuando se presiona Enter
                buscarRepresentante();
            }
        });

        datosEstudiante.setText(" ");
        datosRepresentante.setText(" ");
        datosGrado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCedulaRepre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ButtonConsultar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ButtonTarjeta = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldConceptoPago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonAgregar = new javax.swing.JButton();
        jComboBoxTipoPago = new javax.swing.JComboBox<>();
        ButtonAbono = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ButtonTransferencia = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldReferencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonEfectivo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        datosRepresentante = new javax.swing.JLabel();
        datosEstudiante = new javax.swing.JLabel();
        datosGrado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        datosFecha = new javax.swing.JLabel();
        datosFactura = new javax.swing.JLabel();
        datosTasa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButtonImprimir = new javax.swing.JButton();
        comboEstudiantes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1207, 647));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registrar Pago");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cedula Representante");

        jTextFieldCedulaRepre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaRepreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Estudiante del Representante");

        ButtonConsultar.setBackground(new java.awt.Color(51, 153, 255));
        ButtonConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonConsultar.setText("Consultar");
        ButtonConsultar.setBorderPainted(false);
        ButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        ButtonTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tarjeta-de-credito.png"))); // NOI18N
        ButtonTarjeta.setBorderPainted(false);
        ButtonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTarjetaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Concepto de Pago");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tipo de Pago");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Metodo de Pago");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Efectivo");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Tarjeta");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Transferencia");

        ButtonLimpiar.setBackground(new java.awt.Color(255, 51, 51));
        ButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.setBorderPainted(false);
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonAgregar.setBackground(new java.awt.Color(51, 153, 255));
        ButtonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonAgregar.setText("Agregar");
        ButtonAgregar.setBorderPainted(false);
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });

        jComboBoxTipoPago.setModel(new DefaultComboBoxModel<TipoPagoDTO>());
        jComboBoxTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPagoActionPerformed(evt);
            }
        });

        ButtonAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/radio (1).png"))); // NOI18N
        ButtonAbono.setBorderPainted(false);
        ButtonAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAbonoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Abono");

        ButtonTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transferir.png"))); // NOI18N
        ButtonTransferencia.setBorderPainted(false);
        ButtonTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransferenciaActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("N# de Referencia");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Monto");

        jButtonEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/billete-de-banco (1).png"))); // NOI18N
        jButtonEfectivo.setBorder(null);
        jButtonEfectivo.setBorderPainted(false);
        jButtonEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEfectivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ButtonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAgregar)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jButtonEfectivo))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(79, 79, 79)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(ButtonAbono)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldConceptoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(98, 98, 98)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldReferencia)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel24))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConceptoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonAbono)
                    .addComponent(jButtonEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14))
                            .addComponent(jLabel16))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonAgregar)
                            .addComponent(ButtonLimpiar))
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Datos del Representante");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Datos del Estudiante");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Grado/Año");

        datosRepresentante.setText("agregar datos representante");

        datosEstudiante.setText("agregar datos estudiante");

        datosGrado.setText("agregar datos grado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(datosRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(datosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(datosGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datosRepresentante)
                .addGap(17, 17, 17)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(datosEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosGrado)
                .addGap(8, 8, 8))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Fecha");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("N# Factura");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Tasa Dolar");

        datosFecha.setText("agregar datos fecha");

        datosFactura.setText("agregar datos factura");

        datosTasa.setText("agregar datos tasa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22)
                        .addComponent(datosFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addComponent(datosTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(3, 3, 3)
                .addComponent(datosTasa)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Lista de Pagos Agregados");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 217, 217)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripcion", "Cantidad", "Precio Unidad", "Total Bs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        ButtonImprimir.setBackground(new java.awt.Color(0, 204, 51));
        ButtonImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonImprimir.setText("Imprimir Recibo");
        ButtonImprimir.setBorderPainted(false);
        ButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonImprimirActionPerformed(evt);
            }
        });

        comboEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(ButtonConsultar))
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldCedulaRepre)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboEstudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonImprimir)
                .addGap(525, 525, 525))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCedulaRepre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(comboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(ButtonConsultar))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ButtonImprimir)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1207, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarActionPerformed

        if (estudiante == null) {

            return;
        }

        List<PagoReciboDTO> pagos = pagoControlador.listarPagos(estudiante.getId());

        new consultarPagos().setVisible(true);

    }//GEN-LAST:event_ButtonConsultarActionPerformed

    private void ButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTarjetaActionPerformed
        // TODO add your handling code here:
        metodoPago = "Tarjeta";
        jTextFieldReferencia.setEnabled(false);
        jTextFieldReferencia.setText("");
    }//GEN-LAST:event_ButtonTarjetaActionPerformed

    private void jComboBoxTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPagoActionPerformed
        // TODO add your handling code here:
        tipoPagoDTO = (TipoPagoDTO) jComboBoxTipoPago.getSelectedItem();
        if (tipoPagoDTO == null) {
            return;
        }
        System.out.println(tipoPagoDTO.getCosto());
        String monto = String.valueOf(tipoPagoDTO.getCosto());

        if (tipoPagoDTO.getCategoria().contains("MENSUALIDAD")) {

            mesAPagar = pagoControlador.obtenerMensualidadPendiente(estudiante.getId());

            ButtonAbono.setEnabled(true);
            // Si mesAPagar es null, el estudiante tiene el año solvente.
            if (mesAPagar == null) {
                JOptionPane.showMessageDialog(
                        null,
                        "El estudiante tiene el año solvente.",
                        "Aviso",
                        JOptionPane.INFORMATION_MESSAGE
                );
                ButtonAbono.setEnabled(false);
                return;
            } else if (mesAPagar.tieneSaldoPendiente()) {
                monto = String.valueOf(mesAPagar.calcularPendiente());
                // Si tiene saldo pendiente, es prioridad para pagar.
            }

        } else if (tipoPagoDTO.getCategoria().contains("INSCRIPCIÓN ")) {


            esAbono = false;
            ButtonAbono.setEnabled(false);
        } else {
            esAbono = false;
            ButtonAbono.setEnabled(false);
        }
            jTextFieldMonto.setText(monto);
        jTextFieldCedulaRepre.requestFocusInWindow();
    }//GEN-LAST:event_jComboBoxTipoPagoActionPerformed

    private void ButtonAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAbonoActionPerformed
        // TODO add your handling code here:
        esAbono = !esAbono;
        jTextFieldMonto.setEnabled(esAbono);
    }//GEN-LAST:event_ButtonAbonoActionPerformed

    private void ButtonTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransferenciaActionPerformed
        // TODO add your handling code here:
        metodoPago = "Transferencia";
        jTextFieldReferencia.setEnabled(true);
    }//GEN-LAST:event_ButtonTransferenciaActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
        // TODO add your handling code here:
        metodoPago = "Efectivo";
        jTextFieldReferencia.setEnabled(false);
        jTextFieldReferencia.setText("");
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void comboEstudiantesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboEstudiantesActionPerformed
        // TODO add your handling code here:
        elegirEstudiante();
    }//GEN-LAST:event_comboEstudiantesActionPerformed

    private void ButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonImprimirActionPerformed
        // TODO add your handling code here:
        if (recibo.getDetallesPagoDTOList().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debe de añadir pagos antes de imprimir.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        imprimirPago();
    }//GEN-LAST:event_ButtonImprimirActionPerformed

    private void jTextFieldCedulaRepreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaRepreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaRepreActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        // TODO add your handling code here:
        recibo.borrarRegistros();
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        // TODO add your handling code here:
        if (metodoPago == null) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debes elegir un método de pago.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        } else if (metodoPago.contains("Transferencia") && jTextFieldReferencia.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debes llenar el campo de referencia",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        } else if (jTextFieldConceptoPago.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    null,
                    "Debes llenar el campo de concepto",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        if (metodoPago.contains("Transferencia")) {
            if (jTextFieldReferencia.getText().trim().isEmpty()) {
                return;
            }
        }
        agregarPago();
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    public void buscarRepresentante() {
        String cedula = jTextFieldCedulaRepre.getText().trim();

        if (representante != null) {
            if (representante.getCedula().contains(cedula)) {
                return;
            }
        }

        comboEstudiantes.removeAllItems();

        try{
            this.representante = representanteControlador.buscarRepresentantePorCedula(cedula);

            datosRepresentante.setText(this.representante.getNombre1() + " " + this.representante.getApellido1());
            comboEstudiantes.addItem(null);
            for (EstudianteDTO dto : this.representante.getEstudiantes()) {
            comboEstudiantes.addItem(dto);
            }

            comboEstudiantes.setEnabled(true);


        } catch (NoSuchElementException e) {
            comboEstudiantes.removeAllItems();
            JOptionPane.showMessageDialog(null,
                    e.getMessage(),
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            comboEstudiantes.setEnabled(false);
        }

    }

    public void elegirEstudiante() {

        estudiante = (EstudianteDTO) comboEstudiantes.getSelectedItem();

        if (estudiante != null) {
            datosEstudiante.setText(estudiante.getNombre1() + " " + estudiante.getApellido1());
            datosGrado.setText(estudiante.getGrado());

            mesAPagar = pagoControlador.obtenerMensualidadPendiente(estudiante.getId());

            // Habilitamos los campos deshabilitados
            jTextFieldConceptoPago.setEnabled(true);
            jTextFieldReferencia.setEnabled(true);
            jComboBoxTipoPago.setEnabled(true);
            jButtonEfectivo.setEnabled(true);
            ButtonTarjeta.setEnabled(true);
            ButtonTransferencia.setEnabled(true);
            ButtonConsultar.setEnabled(true);

        } else {
            estudiante = null;
            datosEstudiante.setText(" ");
            datosGrado.setText(" ");

            jTextFieldConceptoPago.setEnabled(false);
            jTextFieldReferencia.setEnabled(false);
            jComboBoxTipoPago.setEnabled(false);
            jButtonEfectivo.setEnabled(false);
            ButtonTarjeta.setEnabled(false);
            ButtonTransferencia.setEnabled(false);
            ButtonConsultar.setEnabled(false);

        }
    }

    public void consultarPagos() {

    }

    public void agregarPago() {

        if (recibo == null) {
            recibo = new PagoReciboDTO();
        }

        BigDecimal montoIngresado;
        boolean tienePendiente;
        try {
            montoIngresado = new BigDecimal(jTextFieldMonto.getText().trim());

            // El costo de referencia es el costo del tipo de pago seleccionado
            BigDecimal costoReferencia = tipoPagoDTO.getCosto();

            // Calcula la diferencia (Costo - MontoIngresado)
            BigDecimal pendiente = costoReferencia.subtract(montoIngresado);

            // Se redondea y se comprueba si el PENDIENTE es mayor que cero (Hay saldo pendiente)
            BigDecimal pendienteRound = pendiente.setScale(2, RoundingMode.HALF_UP);
            tienePendiente = pendienteRound.compareTo(BigDecimal.ZERO) > 0;

            // ** Validación de Monto **
            if (montoIngresado.compareTo(BigDecimal.ZERO) <= 0) {
                JOptionPane.showMessageDialog(null, "El monto a pagar debe ser mayor que cero.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Solo puede ingresar números decimales.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Ocurrió un error al agregar el pago: " + e.getMessage(),
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        DetallesPagoDTO pago;
        AbonoDTO abono;

        if (tipoPagoDTO.getCategoria().contains("MENSUALIDAD")) {

            if (mesAPagar != null) {

                // Si tiene pendiente, entonces es un registro ya existente en la BD con un saldo restante
                if (mesAPagar.tieneSaldoPendiente() && mesAPagar.getId() != null) {

                    pago = crearDetalle();
                    // IMPORTANTE para actualizarlo
                    pago.setId(mesAPagar.getId());
                    pago.setMesCorrespondiente(mesAPagar.getMesCorrespondiente());
                    pago.setTipoPagoDTO(mesAPagar.getTipoPagoDTO());
                    pago.setAnoEscolar(mesAPagar.getAnoEscolar());
                    pago.setMontoTotal(mesAPagar.getMontoTotal());

                    abono = crearAbono();
                    if (abono != null) {pago.addAbonoDTO(abono);} else {return;}

                    // Sino tiene pendiente, entonces es un nuevo mes a pagar
                } else {
                    pago = crearDetalle();
                    pago.setMesCorrespondiente(mesAPagar.getMesCorrespondiente());
                    pago.setTipoPagoDTO(mesAPagar.getTipoPagoDTO());
                    pago.setAnoEscolar(mesAPagar.getAnoEscolar());
                    pago.setMontoTotal(mesAPagar.getMontoTotal());

                    if (pago == null) {return;}

                    if (tienePendiente) {
                        abono = crearAbono();
                        if (abono != null) {pago.addAbonoDTO(abono);} else {return;}
                    }
                }

                recibo.addDetalleDTO(pago);
            }

        } else {
            pago = crearDetalle();
            if (pago == null) {return;}
            recibo.addDetalleDTO(pago);
        }

        jTextFieldConceptoPago.setText("");
        jTextFieldReferencia.setText("");
        jTextFieldMonto.setText(String.valueOf(tipoPagoDTO.getCosto()));
        esAbono = false;
        metodoPago = null;

    }

    public void imprimirPago() {

        try {
            recibo.setIdEstudiante(estudiante.getId());
            recibo.actualizarMontosPagados();
            pagoControlador.guardarPago(recibo);

            // Se eliminan los datos del anterior recibo
            // Esto equivale a iniciar un pago nuevo
            recibo.borrarRegistros();
            comboEstudiantes.removeAllItems();
            estudiante = null;
            representante = null;
            datosRepresentante.setText(" ");
            datosEstudiante.setText(" ");
            datosGrado.setText(" ");

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage(),
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    }

    public AbonoDTO crearAbono() {
        AbonoDTO abono = new AbonoDTO();
        try {
        abono.setMontoAbonado(new BigDecimal(jTextFieldMonto.getText().trim()));
        abono.setDescripcion(jTextFieldConceptoPago.getText().trim());
        abono.setMetodoPago(metodoPago);
        abono.setNumTrans(metodoPago.contains("Transferencia") ? jTextFieldReferencia.getText().trim() : null);
        return abono;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Solo puede ingresar números decimales.",
                    "Alerta",
                    JOptionPane.WARNING_MESSAGE
            );
            return null;
        }
    }

    public DetallesPagoDTO crearDetalle() {

        try {
            DetallesPagoDTO pago = new DetallesPagoDTO();

            AnosEscolaresDTO anoActivo = AnoEscolarMapper.toDTO(anoEscolarControlador.buscarAnoActivo());

            if (anoActivo != null) {
                System.out.println(anoActivo.getId());
                pago.setAnoEscolar(anoActivo);
            } else {
                // Si no hay año activo, esto debería ser un error fatal del sistema.
                throw new RuntimeException("No se encontró un Año Escolar activo para asignar al pago.");
            }

            pago.setTipoPagoDTO((TipoPagoDTO) jComboBoxTipoPago.getSelectedItem());
            pago.setMetodoPago(metodoPago);
            pago.setNumTrans(metodoPago.contains("Transferencia") ? jTextFieldReferencia.getText().trim() : "");
            pago.setDescripcion(jTextFieldConceptoPago.getText().trim());
            pago.setMontoTotal(tipoPagoDTO.getCosto());
            pago.setMontoPagado(new BigDecimal(jTextFieldMonto.getText().trim()));

            return pago;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    null,
                    "Solo puede ingresar números decimales al monto.",
                    "Error",
                    JOptionPane.WARNING_MESSAGE
            );
            return null;
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAbono;
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonConsultar;
    private javax.swing.JButton ButtonImprimir;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonTarjeta;
    private javax.swing.JButton ButtonTransferencia;
    private javax.swing.JComboBox<EstudianteDTO> comboEstudiantes;
    private javax.swing.JLabel datosEstudiante;
    private javax.swing.JLabel datosFactura;
    private javax.swing.JLabel datosFecha;
    private javax.swing.JLabel datosGrado;
    private javax.swing.JLabel datosRepresentante;
    private javax.swing.JLabel datosTasa;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JComboBox<TipoPagoDTO> jComboBoxTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCedulaRepre;
    private javax.swing.JTextField jTextFieldConceptoPago;
    private javax.swing.JTextField jTextFieldMonto;
    private javax.swing.JTextField jTextFieldReferencia;
    // End of variables declaration//GEN-END:variables
}
